/*
 * DC_Motor_config.h
 *
 *  Created on: Feb 17, 2022
 *      Author: hamdy
 */

#ifndef HAL_DC_MOTOR_DC_MOTOR_CONFIG_H_
#define HAL_DC_MOTOR_DC_MOTOR_CONFIG_H_


/*		MOTOR 1 CONFIGURATION	*/
#define MOTOR1_EN_PORT		DIO_u8GROUP_D
#define MOTOR1_EN_PIN		DIO_u8PIN5


#define MOTOR1_INPUT_1_PORT	DIO_u8GROUP_D
#define MOTOR1_INPUT_1_PIN	DIO_u8PIN6

#define MOTOR1_INPUT_2_PORT	DIO_u8GROUP_D
#define MOTOR1_INPUT_2_PIN	DIO_u8PIN7

/*		MOTOR 2 CONFIGURATION	*/
#define MOTOR2_EN_PORT		DIO_u8GROUP_D
#define MOTOR2_EN_PIN		DIO_u8PIN5


#define MOTOR2_INPUT_3_PORT	DIO_u8GROUP_C
#define MOTOR2_INPUT_3_PIN	DIO_u8PIN5

#define MOTOR2_INPUT_4_PORT	DIO_u8GROUP_C
#define MOTOR2_INPUT_4_PIN	DIO_u8PIN6

#endif /* HAL_DC_MOTOR_DC_MOTOR_CONFIG_H_ */
